# Generated by Django 5.2.6 on 2025-09-30 16:57

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        VectorExtension()
    ]
