# Generated by Django 5.2.6 on 2025-09-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_delete_document'),
        ('documents', '0003_document_processed_at_document_status_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='documents.document'),
        ),
    ]
